# frozen_string_literal: true

ActiveRecord::Base.transaction do
  s5d16 = Day.create(sport_id: 1, season_id: 5, date: '14.03.2022'.to_date)
  s5d16.day_players.create(season_id: 5, team_id: 1, player_id: 2)
  s5d16.day_players.create(season_id: 5, team_id: 1, player_id: 29)
  s5d16.day_players.create(season_id: 5, team_id: 1, player_id: 5)
  s5d16.day_players.create(season_id: 5, team_id: 1, player_id: 18)
  s5d16.day_players.create(season_id: 5, team_id: 1, player_id: 38)
  s5d16.day_players.create(season_id: 5, team_id: 1, player_id: 6)
  s5d16.day_players.create(season_id: 5, team_id: 1, player_id: 14)

  s5d16.day_players.create(season_id: 5, team_id: 2, player_id: 1)
  s5d16.day_players.create(season_id: 5, team_id: 2, player_id: 4)
  s5d16.day_players.create(season_id: 5, team_id: 2, player_id: 54)
  s5d16.day_players.create(season_id: 5, team_id: 2, player_id: 62)
  s5d16.day_players.create(season_id: 5, team_id: 2, player_id: 12)
  s5d16.day_players.create(season_id: 5, team_id: 2, player_id: 58)
  s5d16.day_players.create(season_id: 5, team_id: 2, player_id: 11)

  s5d16.day_players.create(season_id: 5, team_id: 3, player_id: 17)
  s5d16.day_players.create(season_id: 5, team_id: 3, player_id: 21)
  s5d16.day_players.create(season_id: 5, team_id: 3, player_id: 57)
  s5d16.day_players.create(season_id: 5, team_id: 3, player_id: 42)
  s5d16.day_players.create(season_id: 5, team_id: 3, player_id: 44)
  s5d16.day_players.create(season_id: 5, team_id: 3, player_id: 48)
  s5d16.day_players.create(season_id: 5, team_id: 3, player_id: 22)

  s5d16.day_players.create(season_id: 5, team_id: 4, player_id: 3)
  s5d16.day_players.create(season_id: 5, team_id: 4, player_id: 8)
  s5d16.day_players.create(season_id: 5, team_id: 4, player_id: 65)
  s5d16.day_players.create(season_id: 5, team_id: 4, player_id: 66)
  s5d16.day_players.create(season_id: 5, team_id: 4, player_id: 67)

  g = Game.create(day_id: s5d16.id, team_left_id: 3, goals_left: 2, goals_right: 0, team_right_id: 2)
  g.goals.create(season_id: 5, team_id: 3, player_id: 42, assist_player_id: 48)
  g.goals.create(season_id: 5, team_id: 3, player_id: 17, assist_player_id: 57)
  g = Game.create(day_id: s5d16.id, team_left_id: 3, goals_left: 0, goals_right: 2, team_right_id: 1)
  g.goals.create(season_id: 5, team_id: 1, player_id: 6, assist_player_id: nil)
  g.goals.create(season_id: 5, team_id: 1, player_id: 2, assist_player_id: nil)
  g = Game.create(day_id: s5d16.id, team_left_id: 1, goals_left: 2, goals_right: 0, team_right_id: 4)
  g.goals.create(season_id: 5, team_id: 1, player_id: 18, assist_player_id: nil)
  g.goals.create(season_id: 5, team_id: 1, player_id: 6, assist_player_id: 18)
  g = Game.create(day_id: s5d16.id, team_left_id: 1, goals_left: 1, goals_right: 0, team_right_id: 2)
  g.goals.create(season_id: 5, team_id: 1, player_id: 29, assist_player_id: nil)
  g = Game.create(day_id: s5d16.id, team_left_id: 1, goals_left: 2, goals_right: 1, team_right_id: 3)
  g.goals.create(season_id: 5, team_id: 1, player_id: 18, assist_player_id: nil)
  g.goals.create(season_id: 5, team_id: 1, player_id: 18, assist_player_id: 2)
  g.goals.create(season_id: 5, team_id: 3, player_id: 22, assist_player_id: nil)
  g = Game.create(day_id: s5d16.id, team_left_id: 1, goals_left: 1, goals_right: 0, team_right_id: 4)
  g.goals.create(season_id: 5, team_id: 1, player_id: 29, assist_player_id: 18)
  g = Game.create(day_id: s5d16.id, team_left_id: 1, goals_left: 0, goals_right: 0, team_right_id: 2)
  g = Game.create(day_id: s5d16.id, team_left_id: 4, goals_left: 0, goals_right: 1, team_right_id: 3)
  g.goals.create(season_id: 5, team_id: 3, player_id: 21, assist_player_id: 17)
  g = Game.create(day_id: s5d16.id, team_left_id: 3, goals_left: 2, goals_right: 1, team_right_id: 2)
  g.goals.create(season_id: 5, team_id: 3, player_id: 21, assist_player_id: 22)
  g.goals.create(season_id: 5, team_id: 3, player_id: 22, assist_player_id: 42)
  g.goals.create(season_id: 5, team_id: 2, player_id: 11, assist_player_id: 4)
  g = Game.create(day_id: s5d16.id, team_left_id: 3, goals_left: 2, goals_right: 0, team_right_id: 1)
  g.goals.create(season_id: 5, team_id: 3, player_id: 21, assist_player_id: nil)
  g.goals.create(season_id: 5, team_id: 3, player_id: 57, assist_player_id: nil)
  g = Game.create(day_id: s5d16.id, team_left_id: 3, goals_left: 1, goals_right: 1, team_right_id: 4)
  g.goals.create(season_id: 5, team_id: 3, player_id: 57, assist_player_id: 42)
  g.goals.create(season_id: 5, team_id: 4, player_id: 8, assist_player_id: nil)
  g = Game.create(day_id: s5d16.id, team_left_id: 1, goals_left: 1, goals_right: 1, team_right_id: 2)
  g.goals.create(season_id: 5, team_id: 1, player_id: 6, assist_player_id: 14)
  g.goals.create(season_id: 5, team_id: 2, player_id: 1, assist_player_id: nil)
  g = Game.create(day_id: s5d16.id, team_left_id: 3, goals_left: 1, goals_right: 1, team_right_id: 4)
  g.goals.create(season_id: 5, team_id: 3, player_id: 42, assist_player_id: 22)
  g.goals.create(season_id: 5, team_id: 4, player_id: 67, assist_player_id: nil)

  g = Game.create(day_id: s5d16.id, team_left_id: 1, goals_left: 1, goals_right: 2, team_right_id: 2)
  g.goals.create(season_id: 5, team_id: 1, player_id: 18, assist_player_id: 2)
  g.goals.create(season_id: 5, team_id: 2, player_id: 11, assist_player_id: 12)
  g.goals.create(season_id: 5, team_id: 2, player_id: 11, assist_player_id: nil)
  g = Game.create(day_id: s5d16.id, team_left_id: 4, goals_left: 0, goals_right: 2, team_right_id: 2)
  g.goals.create(season_id: 5, team_id: 2, player_id: 1, assist_player_id: nil)
  g.goals.create(season_id: 5, team_id: 2, player_id: 1, assist_player_id: 4)
  g = Game.create(day_id: s5d16.id, team_left_id: 3, goals_left: 1, goals_right: 0, team_right_id: 2)
  g.goals.create(season_id: 5, team_id: 3, player_id: 42, assist_player_id: nil)
  g = Game.create(day_id: s5d16.id, team_left_id: 3, goals_left: 0, goals_right: 2, team_right_id: 1)
  g.goals.create(season_id: 5, team_id: 1, player_id: 2, assist_player_id: 6)
  g.goals.create(season_id: 5, team_id: 1, player_id: 38, assist_player_id: nil)
  g = Game.create(day_id: s5d16.id, team_left_id: 4, goals_left: 1, goals_right: 1, team_right_id: 1)
  g.goals.create(season_id: 5, team_id: 4, player_id: 8, assist_player_id: nil)
  g.goals.create(season_id: 5, team_id: 1, player_id: 2, assist_player_id: 38)
  g = Game.create(day_id: s5d16.id, team_left_id: 3, goals_left: 1, goals_right: 1, team_right_id: 2)
  g.goals.create(season_id: 5, team_id: 3, player_id: 22, assist_player_id: 44)
  g.goals.create(season_id: 5, team_id: 2, player_id: 54, assist_player_id: 1)
  g = Game.create(day_id: s5d16.id, team_left_id: 1, goals_left: 2, goals_right: 0, team_right_id: 4)
  g.goals.create(season_id: 5, team_id: 1, player_id: 18, assist_player_id: 38)
  g.goals.create(season_id: 5, team_id: 1, player_id: 6, assist_player_id: nil)
  g = Game.create(day_id: s5d16.id, team_left_id: 1, goals_left: 1, goals_right: 1, team_right_id: 2)
  g.goals.create(season_id: 5, team_id: 1, player_id: 29, assist_player_id: 14)
  g.goals.create(season_id: 5, team_id: 2, player_id: 62, assist_player_id: nil)
  g = Game.create(day_id: s5d16.id, team_left_id: 3, goals_left: 1, goals_right: 0, team_right_id: 4)
  g.goals.create(season_id: 5, team_id: 3, player_id: 48, assist_player_id: 44)
  g = Game.create(day_id: s5d16.id, team_left_id: 3, goals_left: 1, goals_right: 0, team_right_id: 2)
  g.goals.create(season_id: 5, team_id: 3, player_id: 21, assist_player_id: 48)

  s5d16.day_rates!
  Day.last.update!(videos: 'f7rAYNmOIdE,iSh7ys3QTTE,GWZuRJiOBVw,_sgbzMr9Pnw,HrfgEzrLpDU,o9UssrgKVfQ,SeFpqLZ9few,c66q1LZDcq8,K7wdU7zjPas')
end
