# frozen_string_literal: true

ActiveRecord::Base.transaction do
  s5d1 = Day.create(sport_id: 1, season_id: 5, date: '10.01.2022'.to_date)
  s5d1.day_players.create(season_id: 5, team_id: 1, player_id:  1)
  s5d1.day_players.create(season_id: 5, team_id: 1, player_id:  5)
  s5d1.day_players.create(season_id: 5, team_id: 1, player_id: 38)
  s5d1.day_players.create(season_id: 5, team_id: 1, player_id: 14)
  s5d1.day_players.create(season_id: 5, team_id: 1, player_id: 18)
  s5d1.day_players.create(season_id: 5, team_id: 1, player_id: 25)

  s5d1.day_players.create(season_id: 5, team_id: 3, player_id: 57)
  s5d1.day_players.create(season_id: 5, team_id: 3, player_id: 54)
  s5d1.day_players.create(season_id: 5, team_id: 3, player_id: 17)
  s5d1.day_players.create(season_id: 5, team_id: 3, player_id: 9)
  s5d1.day_players.create(season_id: 5, team_id: 3, player_id: 21)
  s5d1.day_players.create(season_id: 5, team_id: 3, player_id: 22)

  g1 = Game.create(day_id: s5d1.id, team_left_id: 3, goals_left: 2, goals_right: 10, team_right_id: 1)
  g1.goals.create(season_id: 5, team_id: 1, player_id: 1, assist_player_id: 17)
  g1.goals.create(season_id: 5, team_id: 1, player_id: 25, assist_player_id: 1)
  g1.goals.create(season_id: 5, team_id: 1, player_id: 25, assist_player_id: 38)
  g1.goals.create(season_id: 5, team_id: 1, player_id: 25, assist_player_id: 1)
  g1.goals.create(season_id: 5, team_id: 1, player_id: 38, assist_player_id: 1)
  g1.goals.create(season_id: 5, team_id: 1, player_id: 25, assist_player_id: nil)
  g1.goals.create(season_id: 5, team_id: 1, player_id: 18, assist_player_id: 1)
  g1.goals.create(season_id: 5, team_id: 1, player_id: 14, assist_player_id: 18)
  g1.goals.create(season_id: 5, team_id: 1, player_id: 18, assist_player_id: 25)
  g1.goals.create(season_id: 5, team_id: 3, player_id: 22, assist_player_id: nil)
  g1.goals.create(season_id: 5, team_id: 3, player_id: 17, assist_player_id: 9)
  g1.goals.create(season_id: 5, team_id: 1, player_id: 1, assist_player_id: 18)
  g2 = Game.create(day_id: s5d1.id, team_left_id: 3, goals_left: 9, goals_right: 4, team_right_id: 1)
  g2.goals.create(season_id: 5, team_id: 3, player_id: 21, assist_player_id: 17)
  g2.goals.create(season_id: 5, team_id: 3, player_id: 22, assist_player_id: 17)
  g2.goals.create(season_id: 5, team_id: 3, player_id: 22, assist_player_id: 17)
  g2.goals.create(season_id: 5, team_id: 3, player_id: 54, assist_player_id: 22)
  g2.goals.create(season_id: 5, team_id: 1, player_id: 1, assist_player_id: 18)
  g2.goals.create(season_id: 5, team_id: 3, player_id: 17, assist_player_id: 22)
  g2.goals.create(season_id: 5, team_id: 3, player_id: 54, assist_player_id: 21)
  g2.goals.create(season_id: 5, team_id: 1, player_id: 25, assist_player_id: 38)
  g2.goals.create(season_id: 5, team_id: 3, player_id: 22, assist_player_id: 21)
  g2.goals.create(season_id: 5, team_id: 1, player_id: 1, assist_player_id: 18)
  g2.goals.create(season_id: 5, team_id: 3, player_id: 57, assist_player_id: nil)
  g2.goals.create(season_id: 5, team_id: 1, player_id: 1, assist_player_id: 18)
  g2.goals.create(season_id: 5, team_id: 3, player_id: 54, assist_player_id: 21)
  g3 = Game.create(day_id: s5d1.id, team_left_id: 3, goals_left: 10, goals_right: 4, team_right_id: 1)
  g3.goals.create(season_id: 5, team_id: 3, player_id: 17, assist_player_id: 54)
  g3.goals.create(season_id: 5, team_id: 1, player_id: 18, assist_player_id: nil)
  g3.goals.create(season_id: 5, team_id: 3, player_id: nil, assist_player_id: nil)
  g3.goals.create(season_id: 5, team_id: 3, player_id: 54, assist_player_id: 22)
  g3.goals.create(season_id: 5, team_id: 1, player_id: 25, assist_player_id: 38)
  g3.goals.create(season_id: 5, team_id: 3, player_id: 22, assist_player_id: 54)
  g3.goals.create(season_id: 5, team_id: 3, player_id: 54, assist_player_id: 22)
  g3.goals.create(season_id: 5, team_id: 1, player_id: 38, assist_player_id: 1)
  g3.goals.create(season_id: 5, team_id: 3, player_id: 9, assist_player_id: 54)
  g3.goals.create(season_id: 5, team_id: 3, player_id: 21, assist_player_id: 22)
  g3.goals.create(season_id: 5, team_id: 3, player_id: 22, assist_player_id: nil)
  g3.goals.create(season_id: 5, team_id: 1, player_id: 18, assist_player_id: 1)
  g3.goals.create(season_id: 5, team_id: 3, player_id: 22, assist_player_id: 17)
  g3.goals.create(season_id: 5, team_id: 3, player_id: 57, assist_player_id: 54)
  g4 = Game.create(day_id: s5d1.id, team_left_id: 3, goals_left: 3, goals_right: 0, team_right_id: 1)
  g4.goals.create(season_id: 5, team_id: 3, player_id: 21, assist_player_id: 22)
  g4.goals.create(season_id: 5, team_id: 3, player_id: 54, assist_player_id: 17)
  g4.goals.create(season_id: 5, team_id: 3, player_id: 17, assist_player_id: 54)

  s5d1.day_rates!
  Day.last.update!(videos: 'RfEYcWnKWKI,AnDrENcscKg,m2rCNlwhrdQ,Qmb4TfLjpuI,4hXvC7b7X3Q,IDELTTbQsc8')
end
