# frozen_string_literal: true

ActiveRecord::Base.transaction do
  s4d29 = Day.new(season_id: @season_id, date: '15.12.2021'.to_date)
  s4d29.day_players.new(season_id: @season_id, team_id: 1, player_id:  6)
  s4d29.day_players.new(season_id: @season_id, team_id: 1, player_id:  5)
  s4d29.day_players.new(season_id: @season_id, team_id: 1, player_id: 29)
  s4d29.day_players.new(season_id: @season_id, team_id: 1, player_id: 38)
  s4d29.day_players.new(season_id: @season_id, team_id: 1, player_id: 52)
  s4d29.day_players.new(season_id: @season_id, team_id: 1, player_id: 14)

  s4d29.day_players.new(season_id: @season_id, team_id: 2, player_id: 13)
  s4d29.day_players.new(season_id: @season_id, team_id: 2, player_id:  2)
  s4d29.day_players.new(season_id: @season_id, team_id: 2, player_id: 10)
  s4d29.day_players.new(season_id: @season_id, team_id: 2, player_id: 23)
  s4d29.day_players.new(season_id: @season_id, team_id: 2, player_id:  4)

  s4d29.day_players.new(season_id: @season_id, team_id: 3, player_id: 54)
  s4d29.day_players.new(season_id: @season_id, team_id: 3, player_id: 48)
  s4d29.day_players.new(season_id: @season_id, team_id: 3, player_id: 50)
  s4d29.day_players.new(season_id: @season_id, team_id: 3, player_id: 61)
  s4d29.day_players.new(season_id: @season_id, team_id: 3, player_id: 21)
  s4d29.day_players.new(season_id: @season_id, team_id: 3, player_id: 22)

  s4d29.day_players.new(season_id: @season_id, team_id: 4, player_id: 1)
  s4d29.day_players.new(season_id: @season_id, team_id: 4, player_id: 9)
  s4d29.day_players.new(season_id: @season_id, team_id: 4, player_id: 58)
  s4d29.day_players.new(season_id: @season_id, team_id: 4, player_id: 8)
  s4d29.day_players.new(season_id: @season_id, team_id: 4, player_id: 2)
  s4d29.save

  g = Game.create(day_id: s4d29.id, team_left_id: 1, goals_left: 1, goals_right: 2, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 21, assist_player_id: 48)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 38, assist_player_id: 18)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 22, assist_player_id: nil)
  g = Game.create(day_id: s4d29.id, team_left_id: 2, goals_left: 2, goals_right: 0, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 13, assist_player_id: 4)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 13, assist_player_id: 23)
  g = Game.create(day_id: s4d29.id, team_left_id: 2, goals_left: 1, goals_right: 1, team_right_id: 1)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 38, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 13, assist_player_id: nil)
  g = Game.create(day_id: s4d29.id, team_left_id: 3, goals_left: 0, goals_right: 2, team_right_id: 1)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 38, assist_player_id: 18)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 6, assist_player_id: 38)
  g = Game.create(day_id: s4d29.id, team_left_id: 2, goals_left: 0, goals_right: 1, team_right_id: 1)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 38, assist_player_id: 52)
  g = Game.create(day_id: s4d29.id, team_left_id: 3, goals_left: 1, goals_right: 1, team_right_id: 1)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 52, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 50, assist_player_id: nil)
  g = Game.create(day_id: s4d29.id, team_left_id: 3, goals_left: 0, goals_right: 1, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 2, assist_player_id: 4)
  g = Game.create(day_id: s4d29.id, team_left_id: 1, goals_left: 0, goals_right: 2, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 4, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 13, assist_player_id: 58)
  g = Game.create(day_id: s4d29.id, team_left_id: 3, goals_left: 1, goals_right: 2, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 61, assist_player_id: 50)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 12, assist_player_id: 4)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 4, assist_player_id: 2)
  g = Game.create(day_id: s4d29.id, team_left_id: 1, goals_left: 2, goals_right: 0, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 6, assist_player_id: 38)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 18, assist_player_id: 38)
  g = Game.create(day_id: s4d29.id, team_left_id: 1, goals_left: 2, goals_right: 1, team_right_id: 4)
  g.goals.create(season_id: @season_id, team_id: 4, player_id: 8, assist_player_id: 61)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 6, assist_player_id: 38)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 52, assist_player_id: 18)
  g = Game.create(day_id: s4d29.id, team_left_id: 1, goals_left: 1, goals_right: 0, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 6, assist_player_id: 18)
  g = Game.create(day_id: s4d29.id, team_left_id: 1, goals_left: 0, goals_right: 0, team_right_id: 2)
  g = Game.create(day_id: s4d29.id, team_left_id: 3, goals_left: 2, goals_right: 0, team_right_id: 4 )
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 48, assist_player_id: 61)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 54, assist_player_id: 21)
  g = Game.create(day_id: s4d29.id, team_left_id: 3, goals_left: 0, goals_right: 1, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: nil, assist_player_id: nil)
  g = Game.create(day_id: s4d29.id, team_left_id: 1, goals_left: 0, goals_right: 2, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 13, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 2, assist_player_id: 4)
  g = Game.create(day_id: s4d29.id, team_left_id: 4, goals_left: 1, goals_right: 2, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 4, player_id: 58, assist_player_id: 1)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 10, assist_player_id: 2)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 2, assist_player_id: 4)
  g = Game.create(day_id: s4d29.id, team_left_id: 3, goals_left: 0, goals_right: 1, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 10, assist_player_id: 4 )
   g = Game.create(day_id: s4d29.id, team_left_id: 1, goals_left: 0, goals_right: 1, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 2, assist_player_id: 23)
  g = Game.create(day_id: s4d29.id, team_left_id: 3, goals_left: 2, goals_right: 1, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 21, assist_player_id: 22)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 13, assist_player_id: 58)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 22, assist_player_id: 21)
  g = Game.create(day_id: s4d29.id, team_left_id: 3, goals_left: 0, goals_right: 3, team_right_id: 1)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 14, assist_player_id: 18)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 6, assist_player_id: 18)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 18, assist_player_id: nil)

  s4d29.day_rates!
  s4d29.season.update(active: false)
  Day.last.update!(videos: 'Rzr3gh-WQ6U,lt0i8gT2GC0,qB3_lWRi560,pbqr8apbfCI,xwkyci05KT0,PkywzwFziSg,plZgGgsqTvc,2TO-bQkvHt4,Rq0sq1vlXRE')
end
