# frozen_string_literal: true

ActiveRecord::Base.transaction do
  s5d9 = Day.new(season_id: @season_id, date: '07.02.2022'.to_date)
  s5d9.day_players.new(season_id: @season_id, team_id: 1, player_id:  2)
  s5d9.day_players.new(season_id: @season_id, team_id: 1, player_id:  5)
  s5d9.day_players.new(season_id: @season_id, team_id: 1, player_id:  6)
  s5d9.day_players.new(season_id: @season_id, team_id: 1, player_id: 14)
  s5d9.day_players.new(season_id: @season_id, team_id: 1, player_id: 18)
  s5d9.day_players.new(season_id: @season_id, team_id: 1, player_id: 29)
  s5d9.day_players.new(season_id: @season_id, team_id: 1, player_id: 38)

  s5d9.day_players.new(season_id: @season_id, team_id: 3, player_id: 21)
  s5d9.day_players.new(season_id: @season_id, team_id: 3, player_id: 22)
  s5d9.day_players.new(season_id: @season_id, team_id: 3, player_id: 49)
  s5d9.day_players.new(season_id: @season_id, team_id: 3, player_id: 48)
  s5d9.day_players.new(season_id: @season_id, team_id: 3, player_id: 57)
  s5d9.day_players.new(season_id: @season_id, team_id: 3, player_id: 61)

  s5d9.day_players.new(season_id: @season_id, team_id: 2, player_id:  4)
  s5d9.day_players.new(season_id: @season_id, team_id: 2, player_id:  9)
  s5d9.day_players.new(season_id: @season_id, team_id: 2, player_id:  1)
  s5d9.day_players.new(season_id: @season_id, team_id: 2, player_id: 65)
  s5d9.day_players.new(season_id: @season_id, team_id: 2, player_id: 58)
  s5d9.day_players.new(season_id: @season_id, team_id: 2, player_id: 35)
  s5d9.save

  g = Game.create(day_id: s5d9.id, team_left_id: 1, goals_left: 2, goals_right: 0, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 29, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 38, assist_player_id: 6)
  g = Game.create(day_id: s5d9.id, team_left_id: 1, goals_left: 1, goals_right: 0, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 6, assist_player_id: nil)
  g = Game.create(day_id: s5d9.id, team_left_id: 1, goals_left: 1, goals_right: 0, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 18, assist_player_id: 29)
  g = Game.create(day_id: s5d9.id, team_left_id: 1, goals_left: 1, goals_right: 1, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 14, assist_player_id: 29)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: nil, assist_player_id: nil)
  g = Game.create(day_id: s5d9.id, team_left_id: 2, goals_left: 1, goals_right: 1, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 1, assist_player_id: 9)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 57, assist_player_id: 22)
  g = Game.create(day_id: s5d9.id, team_left_id: 2, goals_left: 2, goals_right: 0, team_right_id: 1)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 1, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 4, assist_player_id: nil)
  g = Game.create(day_id: s5d9.id, team_left_id: 2, goals_left: 1, goals_right: 1, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 1, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 48, assist_player_id: 21)
  g = Game.create(day_id: s5d9.id, team_left_id: 1, goals_left: 2, goals_right: 1, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 18, assist_player_id: 6)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 18, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 22, assist_player_id: nil)
  g = Game.create(day_id: s5d9.id, team_left_id: 1, goals_left: 2, goals_right: 0, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 18, assist_player_id: 6)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 29, assist_player_id: 38)
  g = Game.create(day_id: s5d9.id, team_left_id: 1, goals_left: 0, goals_right: 0, team_right_id: 3)
  g = Game.create(day_id: s5d9.id, team_left_id: 2, goals_left: 0, goals_right: 2, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 22, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 49, assist_player_id: 22)
  g = Game.create(day_id: s5d9.id, team_left_id: 1, goals_left: 0, goals_right: 0, team_right_id: 3)
  g = Game.create(day_id: s5d9.id, team_left_id: 1, goals_left: 2, goals_right: 0, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 18, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 29, assist_player_id: 18)
  g = Game.create(day_id: s5d9.id, team_left_id: 1, goals_left: 1, goals_right: 0, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 18, assist_player_id: nil)
  g = Game.create(day_id: s5d9.id, team_left_id: 1, goals_left: 2, goals_right: 0, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 29, assist_player_id: 38)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 6, assist_player_id: 38)
  g = Game.create(day_id: s5d9.id, team_left_id: 1, goals_left: 1, goals_right: 1, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 2, assist_player_id: 18)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 21, assist_player_id: 57)
  g = Game.create(day_id: s5d9.id, team_left_id: 2, goals_left: 1, goals_right: 1, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 1, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 22, assist_player_id: nil)
  g = Game.create(day_id: s5d9.id, team_left_id: 1, goals_left: 2, goals_right: 0, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 18, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 18, assist_player_id: 2)
  g = Game.create(day_id: s5d9.id, team_left_id: 1, goals_left: 2, goals_right: 1, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 6, assist_player_id: 2)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 29, assist_player_id: 5)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 21, assist_player_id: 49)
  g = Game.create(day_id: s5d9.id, team_left_id: 1, goals_left: 0, goals_right: 2, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 4, assist_player_id: 1)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 4, assist_player_id: 58)

  s5d9.day_rates!
  Day.last.update!(videos: '5i8-GzUeSUE,5-Uy_t0H7Gw,z5BlyC8Ctdo,4o8o3kmIS44,3zWdg91nz_0,JPkYr3bqDF8,8bpbGsgTCW0,wR0DYt8EE6U,_1vZHB11KoM')
end
