# frozen_string_literal: true

ActiveRecord::Base.transaction do
  s5d8 = Day.new(season_id: @season_id, date: '02.02.2022'.to_date)
  s5d8.day_players.new(season_id: @season_id, team_id: 1, player_id:  5)
  s5d8.day_players.new(season_id: @season_id, team_id: 1, player_id: 18)
  s5d8.day_players.new(season_id: @season_id, team_id: 1, player_id: 38)
  s5d8.day_players.new(season_id: @season_id, team_id: 1, player_id: 52)
  s5d8.day_players.new(season_id: @season_id, team_id: 1, player_id: 25)

  s5d8.day_players.new(season_id: @season_id, team_id: 3, player_id: 21)
  s5d8.day_players.new(season_id: @season_id, team_id: 3, player_id: 22)
  s5d8.day_players.new(season_id: @season_id, team_id: 3, player_id: 42)
  s5d8.day_players.new(season_id: @season_id, team_id: 3, player_id: 48)
  s5d8.day_players.new(season_id: @season_id, team_id: 3, player_id:  4)
  s5d8.day_players.new(season_id: @season_id, team_id: 3, player_id: 12)

  s5d8.day_players.new(season_id: @season_id, team_id: 4, player_id:  3)
  s5d8.day_players.new(season_id: @season_id, team_id: 4, player_id: 14)
  s5d8.day_players.new(season_id: @season_id, team_id: 4, player_id:  8)
  s5d8.day_players.new(season_id: @season_id, team_id: 4, player_id: 65)
  s5d8.day_players.new(season_id: @season_id, team_id: 4, player_id: 66)
  s5d8.save

  g = Game.create(day_id: s5d8.id, team_left_id: 3, goals_left: 8, goals_right: 4, team_right_id: 1)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 21, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 18, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 38, assist_player_id: 18)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 8, assist_player_id: 42)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 22, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 8, assist_player_id: 22)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 22, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 38, assist_player_id: 18)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 8, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 8, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 22, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 3, assist_player_id: 52)
  g = Game.create(day_id: s5d8.id, team_left_id: 3, goals_left: 0, goals_right: 2, team_right_id: 1)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 18, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 18, assist_player_id: 52)
  g = Game.create(day_id: s5d8.id, team_left_id: 4, goals_left: 2, goals_right: 1, team_right_id: 1)
  g.goals.create(season_id: @season_id, team_id: 4, player_id: 8, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 52, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 4, player_id: 8, assist_player_id: 3)
  g = Game.create(day_id: s5d8.id, team_left_id: 4, goals_left: 0, goals_right: 0, team_right_id: 3)
  g = Game.create(day_id: s5d8.id, team_left_id: 1, goals_left: 2, goals_right: 0, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 25, assist_player_id: 52)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 52, assist_player_id: 18)
  g = Game.create(day_id: s5d8.id, team_left_id: 1, goals_left: 2, goals_right: 0, team_right_id: 4)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 18, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 52, assist_player_id: nil)
  g = Game.create(day_id: s5d8.id, team_left_id: 1, goals_left: 2, goals_right: 0, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 18, assist_player_id: 25)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 25, assist_player_id: 18)
  g = Game.create(day_id: s5d8.id, team_left_id: 1, goals_left: 0, goals_right: 0, team_right_id: 4)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 38, assist_player_id: 18)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 38, assist_player_id: 52)
  g = Game.create(day_id: s5d8.id, team_left_id: 1, goals_left: 1, goals_right: 2, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 18, assist_player_id: 38)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 4, assist_player_id: 22)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 22, assist_player_id: 4)
  g = Game.create(day_id: s5d8.id, team_left_id: 4, goals_left: 0, goals_right: 2, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 21, assist_player_id: 22)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 21, assist_player_id: 4)
  g = Game.create(day_id: s5d8.id, team_left_id: 1, goals_left: 0, goals_right: 2, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 48, assist_player_id: 21)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 48, assist_player_id: nil)
  g = Game.create(day_id: s5d8.id, team_left_id: 4, goals_left: 0, goals_right: 2, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 22, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 21, assist_player_id: 12)
  g = Game.create(day_id: s5d8.id, team_left_id: 1, goals_left: 0, goals_right: 0, team_right_id: 3)
  g = Game.create(day_id: s5d8.id, team_left_id: 1, goals_left: 2, goals_right: 0, team_right_id: 4)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 25, assist_player_id: 38)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 25, assist_player_id: 38)
  g = Game.create(day_id: s5d8.id, team_left_id: 1, goals_left: 1, goals_right: 0, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 18, assist_player_id: nil)
  g = Game.create(day_id: s5d8.id, team_left_id: 1, goals_left: 2, goals_right: 0, team_right_id: 4)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 25, assist_player_id: 18)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 18, assist_player_id: 52)
  g = Game.create(day_id: s5d8.id, team_left_id: 1, goals_left: 0, goals_right: 1, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 4, assist_player_id: 21)
  g = Game.create(day_id: s5d8.id, team_left_id: 4, goals_left: 0, goals_right: 1, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: nil, assist_player_id: nil)

  s5d8.day_rates!
  Day.last.update!(videos: 'J1dB3ytxDQ0,CO_LWprqbB4,7r91yKCzjwc,gU3BNN9Qxbc,vl4mtj4uD0M,fXJBv5SnELA,IGGHmfp91-U,ADcNqM0p9rM,dE4DsRGB888')
end
