# frozen_string_literal: true

ActiveRecord::Base.transaction do
  s5d12 = Day.new(season_id: @season_id, date: '21.02.2022'.to_date)
  s5d12.day_players.new(season_id: @season_id, team_id: 1, player_id:  2)
  s5d12.day_players.new(season_id: @season_id, team_id: 1, player_id:  5)
  s5d12.day_players.new(season_id: @season_id, team_id: 1, player_id:  6)
  s5d12.day_players.new(season_id: @season_id, team_id: 1, player_id: 14)
  s5d12.day_players.new(season_id: @season_id, team_id: 1, player_id: 18)
  s5d12.day_players.new(season_id: @season_id, team_id: 1, player_id: 38)

  s5d12.day_players.new(season_id: @season_id, team_id: 2, player_id:  1)
  s5d12.day_players.new(season_id: @season_id, team_id: 2, player_id:  3)
  s5d12.day_players.new(season_id: @season_id, team_id: 2, player_id:  4)
  s5d12.day_players.new(season_id: @season_id, team_id: 2, player_id:  9)
  s5d12.day_players.new(season_id: @season_id, team_id: 2, player_id: 35)
  s5d12.day_players.new(season_id: @season_id, team_id: 2, player_id: 58)

  s5d12.day_players.new(season_id: @season_id, team_id: 3, player_id: 21)
  s5d12.day_players.new(season_id: @season_id, team_id: 3, player_id: 54)
  s5d12.day_players.new(season_id: @season_id, team_id: 3, player_id: 42)
  s5d12.day_players.new(season_id: @season_id, team_id: 3, player_id: 48)
  s5d12.day_players.new(season_id: @season_id, team_id: 3, player_id: 62)
  s5d12.day_players.new(season_id: @season_id, team_id: 3, player_id: 63)
  s5d12.save

  g = Game.create(day_id: s5d12.id, team_left_id: 1, goals_left: 1, goals_right: 0, team_right_id: 2)
  g.goals.create(team_id: 1, player_id: 18, assist_player_id: 38)
  g = Game.create(day_id: s5d12.id, team_left_id: 1, goals_left: 0, goals_right: 0, team_right_id: 3)
  g = Game.create(day_id: s5d12.id, team_left_id: 2, goals_left: 0, goals_right: 1, team_right_id: 3)
  g.goals.create(team_id: 3, player_id: 21, assist_player_id: 62)
  g = Game.create(day_id: s5d12.id, team_left_id: 1, goals_left: 0, goals_right: 0, team_right_id: 3)
  g = Game.create(day_id: s5d12.id, team_left_id: 1, goals_left: 2, goals_right: 0, team_right_id: 2)
  g.goals.create(team_id: 1, player_id: 18, assist_player_id: nil)
  g.goals.create(team_id: 1, player_id: 6, assist_player_id: 38)
  g = Game.create(day_id: s5d12.id, team_left_id: 1, goals_left: 2, goals_right: 0, team_right_id: 3)
  g.goals.create(team_id: 1, player_id: 38, assist_player_id: 2)
  g.goals.create(team_id: 1, player_id: nil, assist_player_id: nil)
  g = Game.create(day_id: s5d12.id, team_left_id: 1, goals_left: 0, goals_right: 2, team_right_id: 2)
  g.goals.create(team_id: 2, player_id: 4, assist_player_id: 1)
  g.goals.create(team_id: 2, player_id: 3, assist_player_id: 1)
  g = Game.create(day_id: s5d12.id, team_left_id: 3, goals_left: 0, goals_right: 2, team_right_id: 2)
  g.goals.create(team_id: 2, player_id: 9, assist_player_id: 58)
  g.goals.create(team_id: 2, player_id: 1, assist_player_id: nil)
  g = Game.create(day_id: s5d12.id, team_left_id: 1, goals_left: 0, goals_right: 1, team_right_id: 2)
  g.goals.create(team_id: 2, player_id: 4, assist_player_id: nil)
  g = Game.create(day_id: s5d12.id, team_left_id: 3, goals_left: 1, goals_right: 2, team_right_id: 2)
  g.goals.create(team_id: 3, player_id: 21, assist_player_id: 42)
  g.goals.create(team_id: 2, player_id: 9, assist_player_id: 1)
  g.goals.create(team_id: 2, player_id: nil, assist_player_id: nil)
  g = Game.create(day_id: s5d12.id, team_left_id: 1, goals_left: 1, goals_right: 1, team_right_id: 2)
  g.goals.create(team_id: 1, player_id: 18, assist_player_id: nil)
  g.goals.create(team_id: 2, player_id: 4, assist_player_id: nil)
  g = Game.create(day_id: s5d12.id, team_left_id: 1, goals_left: 2, goals_right: 1, team_right_id: 3)
  g.goals.create(team_id: 1, player_id: 18, assist_player_id: nil)
  g.goals.create(team_id: 1, player_id: 6, assist_player_id: 18)
  g.goals.create(team_id: 3, player_id: 48, assist_player_id: nil) # 21
  g = Game.create(day_id: s5d12.id, team_left_id: 1, goals_left: 2, goals_right: 0, team_right_id: 2)
  g.goals.create(team_id: 1, player_id: 18, assist_player_id: nil)
  g.goals.create(team_id: 1, player_id: 18, assist_player_id: 38)
  g = Game.create(day_id: s5d12.id, team_left_id: 1, goals_left: 1, goals_right: 1, team_right_id: 3)
  g.goals.create(team_id: 1, player_id: 6, assist_player_id: 2)
  g.goals.create(team_id: 3, player_id: 48, assist_player_id: 42)
  g = Game.create(day_id: s5d12.id, team_left_id: 3, goals_left: 0, goals_right: 2, team_right_id: 2)
  g.goals.create(team_id: 2, player_id: 4, assist_player_id: nil)
  g.goals.create(team_id: 2, player_id: 4, assist_player_id: nil)
  g = Game.create(day_id: s5d12.id, team_left_id: 1, goals_left: 2, goals_right: 0, team_right_id: 2)
  g.goals.create(team_id: 1, player_id: 14, assist_player_id: 38)
  g.goals.create(team_id: 1, player_id: 18, assist_player_id: nil)
  g = Game.create(day_id: s5d12.id, team_left_id: 1, goals_left: 0, goals_right: 0, team_right_id: 3)
  g = Game.create(day_id: s5d12.id, team_left_id: 2, goals_left: 2, goals_right: 1, team_right_id: 3)
  g.goals.create(team_id: 2, player_id: 58, assist_player_id: 4)
  g.goals.create(team_id: 2, player_id: 1, assist_player_id: nil)
  g.goals.create(team_id: 3, player_id: 48, assist_player_id: nil)
  g = Game.create(day_id: s5d12.id, team_left_id: 2, goals_left: 2, goals_right: 1, team_right_id: 1)
  g.goals.create(team_id: 2, player_id: 58, assist_player_id: nil)
  g.goals.create(team_id: 2, player_id: 4, assist_player_id: 58)
  g.goals.create(team_id: 1, player_id: 18, assist_player_id: nil)
  g = Game.create(day_id: s5d12.id, team_left_id: 2, goals_left: 1, goals_right: 2, team_right_id: 3)
  g.goals.create(team_id: 2, player_id: 58, assist_player_id: nil)
  g.goals.create(team_id: 3, player_id: 6, assist_player_id: 42)
  g.goals.create(team_id: 3, player_id: 21, assist_player_id: 48)

  s5d12.day_rates!
  Day.last.update!(videos: 'H2xekWq0j14,41I-c2sQGTQ,gRbiSkS7qb8,89YLcUKVuFI,S7rdnE3vK54,IDuDZHDW4iU,zSnnrGYwUMc,SBEiaxlR1Ew,HE8O7ijEmLM')
end
