# frozen_string_literal: true

ActiveRecord::Base.transaction do
  s5d15 = Day.new(season_id: @season_id, date: '09.03.2022'.to_date)
  s5d15.day_players.new(season_id: @season_id, team_id: 1, player_id: 58)
  s5d15.day_players.new(season_id: @season_id, team_id: 1, player_id: 54)
  s5d15.day_players.new(season_id: @season_id, team_id: 1, player_id: 66)
  s5d15.day_players.new(season_id: @season_id, team_id: 1, player_id:  8)
  s5d15.day_players.new(season_id: @season_id, team_id: 1, player_id: 35)

  s5d15.day_players.new(season_id: @season_id, team_id: 2, player_id:  5)
  s5d15.day_players.new(season_id: @season_id, team_id: 2, player_id: 38)
  s5d15.day_players.new(season_id: @season_id, team_id: 2, player_id: 11)
  s5d15.day_players.new(season_id: @season_id, team_id: 2, player_id:  7)
  s5d15.day_players.new(season_id: @season_id, team_id: 2, player_id:  4)
  s5d15.day_players.new(season_id: @season_id, team_id: 2, player_id: 12)

  s5d15.day_players.new(season_id: @season_id, team_id: 3, player_id: 21)
  s5d15.day_players.new(season_id: @season_id, team_id: 3, player_id: 17)
  s5d15.day_players.new(season_id: @season_id, team_id: 3, player_id: 48)
  s5d15.day_players.new(season_id: @season_id, team_id: 3, player_id: 42)
  s5d15.day_players.new(season_id: @season_id, team_id: 3, player_id: 44)
  s5d15.day_players.new(season_id: @season_id, team_id: 3, player_id: 62)

  s5d15.day_players.new(season_id: @season_id, team_id: 4, player_id: 65)
  s5d15.day_players.new(season_id: @season_id, team_id: 4, player_id:  6)
  s5d15.day_players.new(season_id: @season_id, team_id: 4, player_id:  1)
  s5d15.day_players.new(season_id: @season_id, team_id: 4, player_id: 67)
  s5d15.save

  g = Game.create(day_id: s5d15.id, team_left_id: 3, goals_left: 2, goals_right: 0, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 48, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 42, assist_player_id: nil)
  g = Game.create(day_id: s5d15.id, team_left_id: 3, goals_left: 0, goals_right: 0, team_right_id: 1)
  g = Game.create(day_id: s5d15.id, team_left_id: 2, goals_left: 2, goals_right: 0, team_right_id: 1)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 7, assist_player_id: 38)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 11, assist_player_id: 38)
  g = Game.create(day_id: s5d15.id, team_left_id: 3, goals_left: 0, goals_right: 2, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 11, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: nil, assist_player_id: 38)
  g = Game.create(day_id: s5d15.id, team_left_id: 1, goals_left: 1, goals_right: 0, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 54, assist_player_id: nil)
  g = Game.create(day_id: s5d15.id, team_left_id: 1, goals_left: 2, goals_right: 0, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 8, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 66, assist_player_id: 8)
  g = Game.create(day_id: s5d15.id, team_left_id: 1, goals_left: 0, goals_right: 2, team_right_id: 4)
  g.goals.create(season_id: @season_id, team_id: 4, player_id: 1, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 4, player_id: 6, assist_player_id: 1)
  g = Game.create(day_id: s5d15.id, team_left_id: 4, goals_left: 1, goals_right: 0, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 4, player_id: 6, assist_player_id: nil)
  g = Game.create(day_id: s5d15.id, team_left_id: 3, goals_left: 2, goals_right: 0, team_right_id: 4)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 48, assist_player_id: 21)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 21, assist_player_id: nil)
  g = Game.create(day_id: s5d15.id, team_left_id: 3, goals_left: 1, goals_right: 0, team_right_id: 1)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 48, assist_player_id: nil)
  g = Game.create(day_id: s5d15.id, team_left_id: 3, goals_left: 0, goals_right: 2, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 4, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 11, assist_player_id: nil)
  g = Game.create(day_id: s5d15.id, team_left_id: 4, goals_left: 1, goals_right: 2, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 4, player_id: 1, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 4, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 11, assist_player_id: nil)
  g = Game.create(day_id: s5d15.id, team_left_id: 1, goals_left: 2, goals_right: 0, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 58, assist_player_id: 8)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 8, assist_player_id: 58)
  g = Game.create(day_id: s5d15.id, team_left_id: 1, goals_left: 0, goals_right: 1, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 21, assist_player_id: nil)
  g = Game.create(day_id: s5d15.id, team_left_id: 4, goals_left: 0, goals_right: 0, team_right_id: 3)
  g = Game.create(day_id: s5d15.id, team_left_id: 2, goals_left: 0, goals_right: 1, team_right_id: 1)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 58, assist_player_id: nil)
  g = Game.create(day_id: s5d15.id, team_left_id: 4, goals_left: 0, goals_right: 0, team_right_id: 1)
  g = Game.create(day_id: s5d15.id, team_left_id: 3, goals_left: 1, goals_right: 1, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 21, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 4, assist_player_id: nil)
  g = Game.create(day_id: s5d15.id, team_left_id: 4, goals_left: 1, goals_right: 0, team_right_id: 1)
  g.goals.create(season_id: @season_id, team_id: 4, player_id: 1, assist_player_id: nil)
  g = Game.create(day_id: s5d15.id, team_left_id: 4, goals_left: 0, goals_right: 0, team_right_id: 3)
  g = Game.create(day_id: s5d15.id, team_left_id: 2, goals_left: 2, goals_right: 1, team_right_id: 1)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 11, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 4, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 54, assist_player_id: 58)
  g = Game.create(day_id: s5d15.id, team_left_id: 3, goals_left: 1, goals_right: 1, team_right_id: 2)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 21, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 2, player_id: 11, assist_player_id: nil)
  g = Game.create(day_id: s5d15.id, team_left_id: 2, goals_left: 0, goals_right: 2, team_right_id: 1)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 65, assist_player_id: 67)
  g.goals.create(season_id: @season_id, team_id: 1, player_id: 6, assist_player_id: 12)
  g = Game.create(day_id: s5d15.id, team_left_id: 4, goals_left: 0, goals_right: 2, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 21, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 17, assist_player_id: nil)
  g = Game.create(day_id: s5d15.id, team_left_id: 1, goals_left: 0, goals_right: 2, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 42, assist_player_id: 21)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 21, assist_player_id: 17)
  g = Game.create(day_id: s5d15.id, team_left_id: 4, goals_left: 0, goals_right: 2, team_right_id: 3)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 48, assist_player_id: nil)
  g.goals.create(season_id: @season_id, team_id: 3, player_id: 48, assist_player_id: 44)

  s5d15.day_rates!
  Day.last.update!(videos: 'zswvC1WxXy8,iQitQu5DGLQ,mg4xkJWSXUQ,v-LR8rPWg6Y,Mg8XDCB0dEA,Yhw-nA9A7TU,VhKZAHaAmyE,kyrSP8CErnY,1HJqHNEVSXQ')
end
