ActiveRecord::Base.transaction do
  s4d26 = Day.create(sport_id: 1, season_id: 4, date: '06.12.2021'.to_date)
                                                                    
  s4d26.day_players.create(season_id: 4, team_id: 1, player_id:  5)
  s4d26.day_players.create(season_id: 4, team_id: 1, player_id:  6)
  s4d26.day_players.create(season_id: 4, team_id: 1, player_id: 18)
  s4d26.day_players.create(season_id: 4, team_id: 1, player_id: 25)
  s4d26.day_players.create(season_id: 4, team_id: 1, player_id: 29)
  s4d26.day_players.create(season_id: 4, team_id: 1, player_id:  2)

  s4d26.day_players.create(season_id: 4, team_id: 2, player_id:  4)
  s4d26.day_players.create(season_id: 4, team_id: 2, player_id:  9)
  s4d26.day_players.create(season_id: 4, team_id: 2, player_id: 11)
  s4d26.day_players.create(season_id: 4, team_id: 2, player_id: 12)
  s4d26.day_players.create(season_id: 4, team_id: 2, player_id: 13)
  s4d26.day_players.create(season_id: 4, team_id: 2, player_id: 58)

  s4d26.day_players.create(season_id: 4, team_id: 3, player_id: 21)
  s4d26.day_players.create(season_id: 4, team_id: 3, player_id: 48)
  s4d26.day_players.create(season_id: 4, team_id: 3, player_id: 63)
  s4d26.day_players.create(season_id: 4, team_id: 3, player_id:  8)
  s4d26.day_players.create(season_id: 4, team_id: 3, player_id:  1)
  s4d26.day_players.create(season_id: 4, team_id: 3, player_id: 14)

  g2503 = Game.create(day_id: s4d26.id, team_left_id: 1, goals_left: 2, goals_right: 1, team_right_id: 3)
  g2503.goals.create(season_id: 4, team_id: 1, player_id: 25, assist_player_id: nil)
  g2503.goals.create(season_id: 4, team_id: 1, player_id: 29, assist_player_id: 18)
  g2503.goals.create(season_id: 4, team_id: 3, player_id: 8, assist_player_id: nil)
  g2504 = Game.create(day_id: s4d26.id, team_left_id: 1, goals_left: 1, goals_right: 0, team_right_id: 2)
  g2504.goals.create(season_id: 4, team_id: 1, player_id: 18, assist_player_id: nil)
  g2505 = Game.create(day_id: s4d26.id, team_left_id: 1, goals_left: 2, goals_right: 1, team_right_id: 3)
  g2505.goals.create(season_id: 4, team_id: 1, player_id: 6, assist_player_id: nil)
  g2505.goals.create(season_id: 4, team_id: 1, player_id: 2, assist_player_id: nil)
  g2505.goals.create(season_id: 4, team_id: 3, player_id: 63, assist_player_id: nil)
  g2506 = Game.create(day_id: s4d26.id, team_left_id: 1, goals_left: 0, goals_right: 0, team_right_id: 2)
  g2507 = Game.create(day_id: s4d26.id, team_left_id: 3, goals_left: 2, goals_right: 0, team_right_id: 2)
  g2507.goals.create(season_id: 4, team_id: 3, player_id: 21, assist_player_id: nil)
  g2507.goals.create(season_id: 4, team_id: 3, player_id: 21, assist_player_id: nil)
  g2508 = Game.create(day_id: s4d26.id, team_left_id: 3, goals_left: 2, goals_right: 0, team_right_id: 1)
  g2508.goals.create(season_id: 4, team_id: 3, player_id: 8, assist_player_id: 1)
  g2508.goals.create(season_id: 4, team_id: 3, player_id: 1, assist_player_id: nil)
  g2509 = Game.create(day_id: s4d26.id, team_left_id: 3, goals_left: 0, goals_right: 1, team_right_id: 2)
  g2509.goals.create(season_id: 4, team_id: 2, player_id: 11, assist_player_id: nil)
  g2510 = Game.create(day_id: s4d26.id, team_left_id: 1, goals_left: 2, goals_right: 0, team_right_id: 2)
  g2510.goals.create(season_id: 4, team_id: 1, player_id: 6, assist_player_id: nil)
  g2510.goals.create(season_id: 4, team_id: 1, player_id: 25, assist_player_id: nil)
  g2511 = Game.create(day_id: s4d26.id, team_left_id: 1, goals_left: 0, goals_right: 2, team_right_id: 3)
  g2511.goals.create(season_id: 4, team_id: 3, player_id: 1, assist_player_id: nil)
  g2511.goals.create(season_id: 4, team_id: 3, player_id: 14, assist_player_id: 48)
  g2512 = Game.create(day_id: s4d26.id, team_left_id: 2, goals_left: 0, goals_right: 2, team_right_id: 3)
  g2512.goals.create(season_id: 4, team_id: 3, player_id: 8, assist_player_id: nil)
  g2512.goals.create(season_id: 4, team_id: 3, player_id: 8, assist_player_id: nil)
  g2513 = Game.create(day_id: s4d26.id, team_left_id: 1, goals_left: 0, goals_right: 2, team_right_id: 3)
  g2513.goals.create(season_id: 4, team_id: 3, player_id: 48, assist_player_id: nil)
  g2513.goals.create(season_id: 4, team_id: 3, player_id: 1, assist_player_id: nil)
  g2514 = Game.create(day_id: s4d26.id, team_left_id: 2, goals_left: 0, goals_right: 0, team_right_id: 3)
  g2515 = Game.create(day_id: s4d26.id, team_left_id: 2, goals_left: 1, goals_right: 2, team_right_id: 1)
  g2515.goals.create(season_id: 4, team_id: 2, player_id: 13, assist_player_id: 58)
  g2515.goals.create(season_id: 4, team_id: 1, player_id: nil, assist_player_id: nil)
  g2515.goals.create(season_id: 4, team_id: 1, player_id: nil, assist_player_id: nil)
  g2516 = Game.create(day_id: s4d26.id, team_left_id: 3, goals_left: 0, goals_right: 2, team_right_id: 1)
  g2516.goals.create(season_id: 4, team_id: 1, player_id: 25, assist_player_id: nil)
  g2516.goals.create(season_id: 4, team_id: 1, player_id: 25, assist_player_id: nil)

  g2517 = Game.create(day_id: s4d26.id, team_left_id: 2, goals_left: 0, goals_right: 2, team_right_id: 1)
  g2517.goals.create(season_id: 4, team_id: 1, player_id: 29, assist_player_id: nil)
  g2517.goals.create(season_id: 4, team_id: 1, player_id: 2, assist_player_id: nil)
  g2518 = Game.create(day_id: s4d26.id, team_left_id: 3, goals_left: 2, goals_right: 0, team_right_id: 1)
  g2518.goals.create(season_id: 4, team_id: 3, player_id: 1, assist_player_id: nil)
  g2518.goals.create(season_id: 4, team_id: 3, player_id: 14, assist_player_id: nil)
  g2519 = Game.create(day_id: s4d26.id, team_left_id: 3, goals_left: 1, goals_right: 0, team_right_id: 2)
  g2519.goals.create(season_id: 4, team_id: 3, player_id: 21, assist_player_id: nil)
  g2520 = Game.create(day_id: s4d26.id, team_left_id: 3, goals_left: 0, goals_right: 2, team_right_id: 1)
  g2520.goals.create(season_id: 4, team_id: 1, player_id: 18, assist_player_id: nil)
  g2520.goals.create(season_id: 4, team_id: 1, player_id: 25, assist_player_id: nil)
  g2521 = Game.create(day_id: s4d26.id, team_left_id: 2, goals_left: 1, goals_right: 2, team_right_id: 1)
  g2521.goals.create(season_id: 4, team_id: 2, player_id: 11, assist_player_id: 4)
  g2521.goals.create(season_id: 4, team_id: 1, player_id: 6, assist_player_id: nil)
  g2521.goals.create(season_id: 4, team_id: 1, player_id: 6, assist_player_id: nil)
  g2522 = Game.create(day_id: s4d26.id, team_left_id: 3, goals_left: 1, goals_right: 2, team_right_id: 1)
  g2522.goals.create(season_id: 4, team_id: 3, player_id: 8, assist_player_id: 21)
  g2522.goals.create(season_id: 4, team_id: 1, player_id: 29, assist_player_id: nil)
  g2522.goals.create(season_id: 4, team_id: 1, player_id: 18, assist_player_id: nil)
  g2523 = Game.create(day_id: s4d26.id, team_left_id: 2, goals_left: 0, goals_right: 2, team_right_id: 1)
  g2523.goals.create(season_id: 4, team_id: 1, player_id: 25, assist_player_id: 2)
  g2523.goals.create(season_id: 4, team_id: 1, player_id: 25, assist_player_id: 2)
  g2524 = Game.create(day_id: s4d26.id, team_left_id: 3, goals_left: 0, goals_right: 2, team_right_id: 1)
  g2524.goals.create(season_id: 4, team_id: 1, player_id: 6, assist_player_id: 25)
  g2524.goals.create(season_id: 4, team_id: 1, player_id: 18, assist_player_id: nil)

  s4d26.day_rates!
  Day.last.update!(videos: 'LBMpCADP4N8,DK2CJF0_WFg,38OL0nWS9UI,CeS_JXELyVA,fvnelRFn240,hiXOr36ET9o,E8TLMC0o4JE,SSHdBGJfQbc')
end
